### ISSUE TITLE
Assertion desc failed at libswscale/swscale_internal.h:670

### ISSUE THREAD

**Issue by dwaal** [Manevolent/ffmpeg4j#7]
I tinkered a little bit with your nice ffmpeg4j and used some home videos as source. With ~10% of the videos I had problems.

1. Assertion desc failed at libswscale/swscale_internal.h:670

The error happens when I call FFmpegSourceStream.registerStreams()

More precisely in FFMpegInput.registerStream(FFmpegSourceStream sourceStream, int stream_index) at this line: 

FFmpegError.checkError("avcodec_open2", avcodec.avcodec_open2(ctx, codec, (avutil.AVDictionary) null));

2. Exception in thread "main" com.github.manevolent.ffmpeg4j.FFmpegException: unsupported codec type: 3
	at com.github.manevolent.ffmpeg4j.stream.source.FFmpegSourceStream.registerSubstream(FFmpegSourceStream.java:212)
	at com.github.manevolent.ffmpeg4j.FFmpegInput.registerStream(FFmpegInput.java:136)
	at com.github.manevolent.ffmpeg4j.stream.source.FFmpegSourceStream.registerStreams(FFmpegSourceStream.java:80)
	at incubator.FFmpeg4jExperiments.openVideo(FFmpeg4jExperiments.java:44)
	at tool.FFmpeg4jTree.main(FFmpeg4jTree.java:65)

**Comment by shoeoffhead** [comment]
I also have these issues.

**Comment by AntonKomir** [comment]
Currently "Assertion desc failed at libswscale/swscale_internal.h:734" :(
